---
title: "Homework3"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---


```{r}
install.packages("ggthemes")
library(ggthemes)
library(dplyr)
library(ggplot2)
library(knitr)

nut <- read.csv("~/Desktop/Nutrient_databases/nut_sept22_lwr_dec3.csv", comment.char="#", stringsAsFactors=FALSE)

str(nut)
summary(nut)

ntbl <- tbl_df(nut)

glimpse(ntbl)

```

Change variable names to more intuitive names
```{r}
 ntbl <- ntbl %>%
  rename(species = ASFIS.Scientific.name,
         taxon = ISSCAAP_cat,
         max_length = SLMAX)
View(ntbl)
```

Pull out variables we will use in this analysis
```{r select variables of interest}
ntbl <- ntbl %>%
  select(species, taxon, max_length, TL, CA_mg, EPA_g, DHA_g, ZN_mg, HG_mcg, lwA, lwB, Habitat, Subgroup, Abs_lat)
 View(ntbl)
```

Convert max length to max body size using length-weight conversion (W = a × L^b)
```{r}
ntbl <- ntbl %>%
  mutate(max_size = lwA * (max_length^lwB))

View(ntbl) 
ntbl %>%
  glimpse()
```

How many observations are there per habitat?
```{r}
ntbl %>%
  group_by(Habitat) %>%
  summarize(n_obs = n())
```

```{r}
ntbl %>%
  group_by(Habitat) %>%
  tally
```

What if we want to know the number of species in each habitat?
```{r}
ntbl$Habitat <- as.factor(ntbl$Habitat)

glimpse(ntbl)

ntbl %>%
  group_by(Habitat) %>%
  summarize(n_obs = n(),
            n_species = n_distinct(species), 
            mean_size = mean(max_size))

summary(ntbl)
ggplot(ntbl, aes(x = Habitat, y= max_size) + geom_boxplot(aes(group = Habitat)))

ntbl %>%
  filter(Habitat %in% c("marine", "freshwater")) %>%
  filter(!is.na(max_size)) %>% 
  group_by(taxon) %>%
  summarise_each(funs(mean, median), max_size)

ntbl %>%
  filter(!is.na(max_size)) %>% 
  group_by(taxon) %>%
  summarise_each(funs(mean, median), max_size)

View(ntbl)
```

```{r}

hist(ntbl$max_size)
summary(ntbl$max_size)

ntbl %>%
  filter(Habitat == "marine") %>%
  select(max_size)

ntbl %>% filter(ntbl, Habitat == "marine")



ntbl %>%
  group_by(Habitat) %>%
  summarize(mean_bodysize = max(max_size))

ggplot(ntbl, aes(x = max_size, y = CA_mg, color = Habitat)) + geom_point() +
  scale_x_log10()

ggplot(ntbl, aes(x = log(max_size), y = log(EPA_g), color = Habitat)) + geom_point()

p <- ggplot(data=ntbl, aes(x=Abs_lat, y=log(EPA_g), group=Habitat, colour=Habitat))
p + geom_point() 
p + stat_summary(aes(y = log(EPA_g)), fun.y=mean, geom = "point") + geom_hline(aes(yintercept=log(0.5)))
             
```

