---
title: "RDI"
output: 
  html_document: 
    keep_md: yes
---

```{r warning= FALSE}
library(ggplot2)
library(plotrix)
library(broom)
library(ggthemes)
suppressPackageStartupMessages(library(dplyr))
library(knitr)
suppressPackageStartupMessages(library(Hmisc))
suppressPackageStartupMessages(library(robustbase))
library(tidyr)
library(MuMIn)

nut <- read.csv("~/Desktop/Nutrient_databases/nut_sept22_lwr_dec3.csv", comment.char="#", stringsAsFactors=TRUE, na.strings=c("",".","NA"))
ntbl <- tbl_df(nut)

```

#### Data cleaning and wrangling

Let's change variable names to more intuitive names.

```{r warning= FALSE}
 ntbl <- ntbl %>%
  mutate(HG_mcg = as.numeric(HG_mcg)) %>% 
   rename(species = ASFIS.Scientific.name,
         taxon = ISSCAAP_cat,
         max_length = SLMAX) 

```

Pull out variables we will use in this analysis. 

```{r select variables of interest}
ntbl <- ntbl %>%
  select(species, taxon, max_length, TL, CA_mg, EPA_g, DHA_g, FE_mg, ZN_mg, HG_mcg, lwA, lwB, Habitat, Subgroup, Abs_lat)

```

Convert max length to max body size using length-weight conversion (W = a × L^b). For more information about this conversion approach, see this [explanation](http://www.fishbase.ca/manual/FishBaseThe_LENGTH_WEIGHT_Table.htm) on FishBase. 
```{r warning= FALSE}
ntbl <- ntbl %>%
  mutate(max_size = (lwA * (max_length^lwB)/1000))
```

```{r warning= FALSE}
ntbl.multi <- ntbl %>% 
  group_by(species) %>% 
  filter(!is.na(ZN_mg)) %>% 
  filter(!is.na(CA_mg)) %>% 
  filter(!is.na(FE_mg)) %>% 
  filter(!is.na(EPA_g)) %>%
  filter(!is.na(DHA_g))
  
View(ntbl.multi)


ntbl.CA <- ntbl %>%
  filter(!is.na(max_size)) %>% 
  filter(!is.na(CA_mg)) %>% 
  filter(!is.na(taxon))

ntbl.EPA <- ntbl %>%
  filter(!is.na(Abs_lat)) %>% 
  filter(!is.na(EPA_g)) %>% 
  filter(!is.na(taxon))

ntbl.HG <- ntbl %>%
  filter(!is.na(Abs_lat)) %>% 
  filter(!is.na(HG_mcg)) %>% 
  filter(!is.na(taxon))

ntbl.ZN <- ntbl %>%
  filter(!is.na(max_size)) %>% 
  filter(!is.na(ZN_mg)) %>% 
  filter(!is.na(taxon))

ntbl.FE <- ntbl %>%
  filter(!is.na(max_size)) %>% 
  filter(!is.na(FE_mg)) %>% 
  filter(!is.na(taxon))

ntbl.DHA <- ntbl %>%
  filter(!is.na(Abs_lat)) %>% 
  filter(!is.na(DHA_g)) %>% 
  filter(!is.na(taxon)) %>% 
  filter(!is.na(TL)) %>% 
  filter(!is.na(Habitat)) %>% 
  filter(!is.na(max_size))

ntbl.EPA <- ntbl %>%
  filter(!is.na(Abs_lat)) %>% 
  filter(!is.na(EPA_g)) %>% 
  filter(!is.na(taxon)) %>% 
  filter(!is.na(TL)) %>% 
  filter(!is.na(Habitat)) %>% 
  filter(!is.na(max_size))

str(ntbl.HG)

```

```{r}

```

