---
title: "FD.null"
output: 
  html_document: 
    keep_md: yes
---

```{r warning = FALSE}
#### Load packages
suppressPackageStartupMessages(library(FD))
library(ggplot2)
library(broom)
suppressPackageStartupMessages(library(dplyr))
library(tidyr)
library(readr)

#### Step 1. Import the data

ntbl <- read_csv("/Users/Joey/Documents/Nutrient_Analysis/data/ntbl.csv")
ntbl <- tbl_df(ntbl)
str(ntbl)
fd.null <- read_csv("/Users/Joey/Documents/Nutrient_Analysis/data/fd.null.csv")
fd.null <- as.vector(fd.null)


ntbl.cambgang <- ntbl %>% 
  filter(species %in% c("Labeo rohita", "Cirrhinus mrigala", "Channa punctata", "Cyprinidae", "Rasbora tawarensis", "Channa marulius", "Channa micropeltes", "Amblypharyngodon mola", "Macrognathus aculeatus", "Ambassidae", "Esomus danricus", "Corica soborna", "Cirrhinus cirrhosus", "Puntius sophore", "Hypophthalmichthys molitrix"))

unique(ntbl.cambgang$species)


#### Step 2. Create RDI profiles
ntbl.RDI.mic <- ntbl %>% 
  group_by(species) %>%
  summarise(mean.CA = mean(CA_mg, na.rm = TRUE),
            mean.EPA = mean(EPA_g, na.rm = TRUE), 
            mean.DHA = mean(DHA_g, na.rm = TRUE), 
            mean.ZN = mean(ZN_mg, na.rm = TRUE), 
            mean.FE = mean(FE_mg, na.rm = TRUE)) %>% 
  mutate(RDI.CA = (mean.CA > 300)) %>% 
  mutate(RDI.FE = (mean.FE > 4.5)) %>% 
  mutate(RDI.ZN = (mean.ZN > 2.75)) %>% 
  mutate(RDI.EPA = (mean.EPA > 0.25)) %>% 
  mutate(RDI.DHA = (mean.DHA > 0.25)) %>%
  mutate(RDI.micro.tot = rowSums(.[7:11])) %>% 
  filter(!is.na(RDI.micro.tot))

ntbl$species <- as.factor(ntbl$species)
ntbl.RDI <- ntbl %>% 
  group_by(species) %>%
  summarise(mean.CA = mean(CA_mg, na.rm = TRUE),
            mean.EPA = mean(EPA_g, na.rm = TRUE), 
            mean.DHA = mean(DHA_g, na.rm = TRUE), 
            mean.ZN = mean(ZN_mg, na.rm = TRUE), 
            mean.FE = mean(FE_mg, na.rm = TRUE)) %>%
  mutate(RDI.CA = ifelse(mean.CA > 300, 1, 0)) %>% 
  mutate(RDI.FE = ifelse(mean.FE > 4.5, 1, 0)) %>% 
  mutate(RDI.ZN = ifelse(mean.ZN > 2.75, 1, 0)) %>% 
  mutate(RDI.EPA = ifelse(mean.EPA > 0.25, 1, 0)) %>% 
  mutate(RDI.DHA = ifelse(mean.DHA > 0.25, 1, 0)) %>%
  mutate(RDI.micro.tot = rowSums(.[7:11])) %>% 
  filter(!is.na(RDI.micro.tot)) %>% View
  arrange(., RDI.micro.tot) %>% 
  select(., 7:11)



write_csv(ntbl.RDI, "RDImat.csv")

#### Step 3. Turn RDI df into a matrix
ntbl.matrix.mic <- data.matrix(ntbl.RDI.mic[, 2:6])
rownames(ntbl.matrix.mic) <- ntbl.RDI.mic$species


#### Step 4. Sample 29 species from the RDI matrix randomly
randsp.data <- ntbl.matrix.mic[sample(1:length(row.names(ntbl.matrix.mic)), 29, replace = FALSE),]

# OR the dplyr way:

# rand.spd <- replicate(10, sample_n(ntbl.RDI.mic, 50, replace = FALSE))
# str(rand.spd)

### Step 5. Run the functional diversity function on the random subset
rand.fd <- dbFD(randsp.data, messages = FALSE)
rand.fd$FDiv

#### repeat this subsampling process many times...to generate a mean expected FD value.

# fdiv.exp <- vector()
# for (i in 1:5000) {
#   randsp.data<- ntbl.matrix.mic[sample(1:length(row.names(ntbl.matrix.mic)), 29, replace = FALSE),]
#   fdiv.exp[i] <- dbFD(randsp.data, messages = FALSE)$FDiv
# }

## Alternative to the for loop, using the replicate function:
fd.exp <- function(mat, n) {
  randsp.data<- mat[sample(1:length(row.names(mat)), n, replace = FALSE),]
  fdiv.exp<- dbFD(randsp.data, messages = FALSE)$FDiv
}

# Replicate the function 10000 times, and save 10,000 random FD values as a csv
# fd.null <- as.vector(replicate(10000, fd.exp(ntbl.matrix.mic, 29)))
# fd.null <- as.data.frame(fd.null)
# write_csv(fd.null, "fd.null.csv")

###Cambodia, which has 4 species

fd.null.cam <- as.vector(replicate(1000, fd.exp(ntbl.matrix.mic, 4)))
mean(fd.null.cam)
hist(fd.null.cam)
abline(v = 0.9047908, col = "red") #this is the value of FDiv I calculated for the Cambodia species
abline(v = 0.8944811, col = "blue") #95% quantile
abline(v = 0.7021020, col = "blue") # 5% quantile
quantile(fd.null.cam, c(.05, .95))


#### Step 6. 
# Take the mean FDiv value, and compare my observed FDiv value to mean expected value.

summary(fd.null)
View(fd.null)
fd.null$fd.null <- as.numeric(fd.null$fd.null)
quantile(fd.null$fd.null, c(.05, .95))
hist(fd.null$fd.null)
abline(v = 0.6243078, col = "red") #this is the value of FDiv I calculated for the US species
abline(v = 0.5915841, col = "blue")
abline(v = 0.6947158, col = "blue")
```


##### Beta-diversity attempts!
```{r}
library(betapart)
library(picante)
library(vegan)
library(dplyr)

?betadiver

ntbl.mic.um <- ntbl %>% 
  group_by(species) %>% 
  summarise(mean.CA = mean(CA_mg*1000, na.rm = TRUE),
            mean.EPA = mean(EPA_g*1000, na.rm = TRUE), 
            mean.DHA = mean(DHA_g*1000, na.rm = TRUE), 
            mean.ZN = mean(ZN_mg*1000, na.rm = TRUE), 
            mean.FE = mean(FE_mg*1000, na.rm = TRUE)) %>%
  filter(!is.na(mean.CA)) %>%
  filter(!is.na(mean.EPA)) %>%
  filter(!is.na(mean.DHA)) %>%
  filter(!is.na(mean.ZN)) %>%
  filter(!is.na(mean.FE))

matrix.mic <- data.matrix(ntbl.mic.um[, 2:6])
rownames(matrix.mic) <- ntbl.mic.um$species 

b <- vegdist(matrix.mic, method = "bray", binary = FALSE)
str(b)
summary(b)
betadiv <- betadiver(b)
summary(betadiv)
plot(betadiv)

###replicate the bray-curtis calcs
bd.exp <- function(mat, n) {
  randsp.data<- mat[sample(1:length(row.names(mat)), n, replace = FALSE),]
  bdiv.exp<- mean(vegdist(randsp.data, method = "bray", binary = FALSE))
}

bd.null <- as.vector(replicate(10000, bd.exp(matrix.mic, 29)))



## find the 5% and 95% quantiles
quantile(bd.null, c(.05, .95))

##plot the quantiles and the calculated BC value for the whole fish dataset
png("bc.null.png", width = 6, height = 4, units = 'in', res = 300)
hist(bd.null)
abline(v = 0.5906185, col = "red", lwd = 3)
abline(v = 0.5431548, col = "cadetblue", lty = 3, lwd = 3)
abline(v = 0.6334351, col = "cadetblue", lty = 3, lwd = 3)
dev.off()

# RDI.um <- RDI.mat %>% 
#   mutate_each(funs(um = .*1000)) %>% 
#   mutate_each(funs(um = as.integer(.)))
```